C THIS FILE STORES ALL THE BASIS FUNCTIONS

C      WHEN N=1, IT CALCULATES SATURATED VAPOR PRESSURE
C      WHEN N=2, IT CALCULATES THE DERIVATIVE OF SATURATED VAPOR PRESSURE TO T 
      DOUBLE PRECISION FUNCTION PSAT(N,TK)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z) 
      IF (N.EQ.1) THEN
      PSAT=6.11D2*EXP(17.27*(TK-273.15)/(TK-35.85))    !SATURATED VAPOR PRESSURE AT TEMP TK
      ELSEIF (N.EQ.2)THEN
      PSAT=2.504D6/(TK-35.85D0)**2.D0*
     1    EXP(17.27D0*(TK-273.15D0)/(TK-35.85D0))      !DELTA P  = DP/DT  
      ENDIF
      RETURN
      END


C       DIFFUSION OF WATER VAPOR IN THE SOIL, TORTUOSITY AND AIR CONTENT
C       SEE NOTEBOOK3 P44
      DOUBLE PRECISION FUNCTION DV (POR,SW,TK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      TAO=POR**(1.D0/3.D0)*(1-SW)**(7.D0/3.D0)
      THEA=POR*(1-SW)
      DA=2.29D-5*(TK/273.15D0)**1.75D0
      DV=TAO*THEA*DA
      RETURN
      END

C       DIFFUSION OF WATER VAPOR IN THE AIR
      DOUBLE PRECISION FUNCTION DA (TK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DA=2.29D-5*(TK/273.15D0)**1.75D0
      RETURN
      END




C      FUNCTION FYM IS TO CALCULATE THE OSMOTICAL POTENTIAL FROM PORE WATER PRESSURE
C     INPUT CONDITIONS 
C      P -- PORE WATER PRESSURE [PA]
C     ROU - PURE WATER DENSITY [KG/M3]
C     G  -- GRAVATIONAL ACCERATION [M/S2]
      DOUBLE PRECISION FUNCTION FYM(P)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DATA  ROU/1.D3/, G/9.8D0/
      SAVE ROU,G
      FYM=P/ROU/G
      RETURN 
      END
C      FUNCTION FYO IS TO CALCULATE THE OSMOTICAL POTENTIAL FROM PORE WATER PRESSURE
C     CALLED FUNCTION AND SUBROUTINES:
C     CHI(C) TO GET OSMOTIC COEFFICIENTS, BASED ON ROBINSON AND STOKES (1965)
      DOUBLE PRECISION FUNCTION FYO(C,T)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DATA  RC/8.314472D+0/,G/9.8D0/,STM/5.85D-2/
      SAVE RC,G,STM
      FYO=-2.D0*CHI(C)*C*RC*T/G/STM
      RETURN 
      END


C     FUNCTION HR IS TO CALCULATE THE RELATIVE HUMIDITY ACCORDING TO KELVEN'S EQUATION
      DOUBLE PRECISION FUNCTION HR(FM,FO,T)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DATA  RC/8.314472D+0/,G/9.8D0/,WMW/1.8D-2/
      SAVE RC,G,WMW
      HR=EXP((FM+FO)*G*WMW/RC/T)
      RETURN 
      END



      SUBROUTINE AEROSIST(RAVT,MAR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      RETURN
      END

      DOUBLE PRECISION FUNCTION CHI (C)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHI=.9D0+2.6D-3*(C/(1-C))*1.D3+2.6D-3*((C/(1-C))*1.D3)**5.3D-2           ! EMPIRICAL EQUATION
      RETURN
      END
