# this folder stores all of the basic functions

C      WHEN N=1, IT CALCULATES SATURATED VAPOR PRESSURE
C      WHEN N=2, IT CALCULATES THE DERIVATIVE OF SATURATED VAPOR PRESSURE TO T 
      DOUBLE PRECISION FUNCTION PSAT(N,TK)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z) 
      IF (N.EQ.1) THEN
      PSAT=6.11D2*EXP(17.27*(TK-273.15)/(TK-35.85))    !SATURATED VAPOR PRESSURE AT TEMP TK
      ELSEIF (N.EQ.2)THEN
      PSAT=2.504D6/(TK-35.85D0)**2.D0*
     1    EXP(17.27D0*(TK-273.15D0)/(TK-35.85D0))      !DELTA P  = DP/DT  
      ENDIF
      RETURN
      END


C       DIFFUSION OF WATER VAPOR IN THE SOIL, TORTUOSITY AND AIR CONTENT
C       SEE NOTEBOOK3 P44
      DOUBLE PRECISION FUNCTION DV (POR,SW,TK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      TAO=POR**(1.D0/3.D0)*(1-SW)**(7.D0/3.D0)
      THEA=POR*(1-SW)
      DA=2.29D-5*(TK/273.15D0)**1.75D0
      DV=TAO*THEA*DA
      RETURN
      END

C       DIFFUSION OF WATER VAPOR IN THE AIR
      DOUBLE PRECISION FUNCTION DA (TK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DA=2.29D-5*(TK/273.15D0)**1.75D0
      RETURN
      END


      DOUBLE PRECISION FUNCTION CHI (C)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHI=.9D0+2.6D-3*(C/(1-C))*1.D3+2.6D-3*((C/(1-C))*1.D3)**5.3D-2           ! EMPIRICAL EQUATION
      RETURN
      END

