#!/bin/bash
ifort -debug \
      main.f \
      slap.f \
      SinkareaRegular.f \
      suterr.f \
      init.f \
      hypergeometric.f \
      tridiag.f \
      ft03.f90 \
      vapor.f \
      heat.f \
      surfrsis.f \
      unsat.f \
      perfilm.f \
      bctime.f  \
      others.f  \
      -o sutraDebug 
