C *** ASSIGNING EVAPORATION RATE THROUGH RELEVANT FUNCTIONS
C *** WHEN QET=1 THEN USING PENMAN (1948) EQUATION,
! THIS IS FURTHER MODIFIED BY KONUKCU (2007)
C *** WHEN QET=2 THEN USING PDV (1957) EQUATION.
C *** SEE NOTEBOOK2 PAGE47 FOR FURTHER EXPLANATION 
      SUBROUTINE EVAPORATION (AET,PC,CC,RHO,WMA,SM,HM,HO,DELL,TAUTH,DFR
     1,PWFR,PCFR,RSC,TSK,POR,SW,KREG,Y)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /ET/ QET,UET,PET,UVM,NGT,ITE,TMA,TMI,ALF,RS,RH,AP,BP,U2,
     1   TSD,SCF
      COMMON /AERORESIS/ RAVT,RAVS,SWRAT
      COMMON /SALTRESIS/ AR,BR
      COMMON /GRAVEC/ GRAVX,GRAVY,GRAVZ 
      COMMON /PARAMS/ COMPFL,COMPMA,DRWDU,CW,CS,RHOS,SIGMAW,SIGMAS,     
     1   RHOW0,URHOW0,VISC0,PRODF1,PRODS1,PRODF0,PRODS0,CHI1,CHI2   
     2   ,DVIDU,RELPW,PERMVAC,SURFT,PI,ELECTRC,BOTZC,CL,CA,DMAIR,
     3   RC,SATM,STM,GVA,WMW,ZETA
      COMMON /CONTRL/ GNUP,GNUU,UP,DTMULT,DTMAX,ME,ISSFLO,ISSTRA,ITCYC,
     1   NPCYC,NUCYC,NPRINT,NBCFPR,NBCSPR,NBCPPR,NBCUPR,IREAD, 
     2   ISTORE,NOUMAT,IUNSAT,KTYPE,MET,MAR,MSR,MSC,MHT,MVT,MFT,MRK
      DIMENSION KTYPE(2)
      DOUBLE PRECISION SBC,GAM,Y
      DATA  SBC /4.896E-9/, GAM /6.6E-2/, DP/1.8E+0/
      SAVE SBC,GAM,DP

C     AET  -- ACTUAL EVAPORATION RATE [MM/DAY]
C     PC   -- PRESSURE AT THE SPECIFIED NODE [KG/M/S2]
C     CC   -- CONCENTRATION AT THE SPECIFIED NODE  [KG/KG]
C     RHO  -- DENSITY OF THE SPECIFIED NODE [KG/M2]
C     TMA  -- AIR TEMPERATURE [CELSIUS]
C     TMI  -- SOIL SURFACE TEMPERATURE [CELSIUS]
C     TM   -- MEAN DAILY AIR TEMPERATURE [CELSIUS]
C     DLT  -- SLOPE OF SATURATION VAPOR PRESSURE CURVE E/T [KPA/CELSIUS]
C     VLH  -- LATENT HEAT OF VAPORISATION [J/KG] 
C     ALF  -- ALBEDO [I]
C     RS   -- SHORT WAVE INCOMING RADIATION  [MJ/M2/DAY]
C     RH   -- RELATIVE HUMIDITY 0<RH<1
C     ED   -- SATURATED VAPOUR PRESSURE AT DEW POINT [KPA]
C     EMI  -- EMMISIVITY [I]
C     RN   -- NET RADIANT ENERGY 
C     GAM  -- PSYCHROMETRIC CONSTANT [KPA/CELSIUS]
C     EO(NOT ZERO)   -- SATURATED VAPOUR PRESSURE AT MEAN DAILY AIR
C                        TEMP. (TM) [PA]
C     FU   -- WIND FUNCTION [MJ/M2/KPA/DAY]
C     AP,BP-- PARAMETER IN WIND FUNCTION
C     U2   -- DAILY MEAN WIND SPEED AT 2M ABOVE GROUND [KM/DAY]
C     RC   -- UNIVERSAL GAS CONSTANT [J/MOL/K]
C     WMW   -- MOLECULAR WEIGHT OF WATER [KG/MOL]
C     TS   -- SOIL TEMPERATURE [CELSIUS]
C     DP   -- VAN'T HOFF DISSOCIATION FACTOR
C     STM  -- MOLECULAR WEIGHT OF NACL [KG/MOL]
C     FIO(NOT ZERO)  -- OSMOTIC POTENTIALS (M)
C     HO(NOT ZERO)   -- OSMOTIC PARAMETER
C     RHOW0   -- INITIAL WATER DENSITY (KG/M3)
C      TSK   -- TEMPERATURE AT THAT NODE
C      TMAK   -- TEMPERATURE AT THAT NODE  
C ... PEMAN METHOD ...      
      IF (MET.EQ.1) THEN ! USING PENMAN EVAPORATION EQUATION
      TMAK=273.15D0+TMA                                   
      ! AIR TEMPERATURE TMAK=(TMA-273.15D0)
C     LATENT HEAT FOR VAPORIZATION   [J/KG]
      VLH=(2.50025-0.002365*(TMAK-273.15D0))*1.D6   
! CAPITAL GAMA FOR CALCULATING DEW POINT TEMP.
      CGA=17.271*(TMAK-273.15D0)/(237.7+(TMAK-273.15D0))+LOG(RH)        
    ! DEW POINT [K]
      TD=237.7*CGA/(17.271-CGA)+273.15                            
C      EMI=0.34-0.139*SQRT(ED)            
C      RN=RS*(1-ALF)-EMI*SBC*((TMA+273.15)**4+(TMI+273.15)**4)/2
C      FU=AP+BP*U2
C.....EQUATION FROM KONUKCU OBVIOUSLY THIS EQUATION IS DODGY
C      FIO=-RC*(TS+273.15)*(CC*RHO/STM)*DP/DABS(GRAVY)/RHO
C.....END OF KONUKCU EQUATION
C.....START OF FUJIMAKI EQUATION FOR CALCULATING SOIL RELATIVE HUMIDITY
C..... 0.204=0.102*2
  ! THIS IS (RN-G) WHICH CHANGES OVER TIME
      RMG=0.D0                            
      HO=EXP(-WMW*2.D0*CHI(CC)*CC/STM)
      HM=EXP(WMW*PC/RHOW0/RC/TSK)
      DFR=RSC                                          ! OUTPUT 
      PWFR=HO                                          ! OUTPUT
      PCFR=HM                                          ! OUTPUT

      CA=1013.D0   ! SPECIFIC HEAT OF AIR AT CONSTANT TEMP [1013 J/KG/K]
      PA=1.01D5    ! ATMOSPHEREIC PRESSURE                 [PA]
      DMOA=0.02897       ! MOLECULAR WEIGHT OF AIR (KG/MOL)       

      RHOA=PA*DMOA/RC/TMAK
      GAMA=66.D0                      ! PSYCHOMETRIC CONSTANT  [PA/K]
      DLNUM=HO*HM*PSAT(2,TMAK)*RMG
      DRNUM=CA*RHOA/RAVT*(HO*HM*PSAT(1,TMAK)-PSAT(1,TD))
      DENO=VLH*RHOW0*(HO*HM*PSAT(2,TMAK)+GAMA*(RAVT+RSC)/RAVT)
      AET=-(DLNUM+DRNUM)/DENO
C      FIO=-0.204*X*CC/STM*RC*(TS+273.15)
C.....END OF FUJIMAKI EQUATION
C      AA=PC/RHO
C      BB=PC/RHO/9.81
C      HM=EXP(WMW*(PC/RHO)/RC/(TS+273.15))
C      HO=EXP(WMW*DABS(GRAVY)*FIO/RC/(TS+273.15))

C      AET=-(HM*HO*DLT*RN+GAM*(HM*HO*EO-ED)*FU)/VLH/(DLT+GAM)
C        IF (AET.GT.0) THEN
C        AET=0
C        ENDIF

C ... DIRECT METHOD OF CALCULATING EVAPORATION   
     ! SEE NOTEBOOK3 P5
 ! USING VAPOR FLOW EQUATION
      ELSEIF (MET.EQ.2) THEN                         
                            ! AIR TEMPERATURE TMAK=(TMA-273.15D0)
      TMAK=273.15D0+TMA     
      TERM1=WMW/RHOW0/RC
C RELATIVE HUMIDITY INDUCED BY OSMOTICAL POTENTIAL 
      HO=EXP(-WMW*2.D0*CHI(CC)*CC/STM)      
C RELATIVE HUMIDITY INDUCED BY MATRIC POTENTIAL
      HM=EXP(WMW*PC/RHOW0/RC/TSK)         
  ! DFR, PWFR AND PCFR IS USED FOR OUTPUT IN .BCOF
      DFR=RSC                                       
      PWFR=HO
      PCFR=HM
      SURF=SURFRSIS(PC,POR,SW,MSR,KREG,TSK,Y)
      AET=-TERM1*(PSAT(1,TSK)*HO*HM/TSK-PSAT(1,TMAK)*RH/TMAK)/(RAVT
     1 +SURF+RSC)
      WRITE(48,49) SURF,SW,PC,TSK,HO,HM,AET
49    FORMAT(7(1PE15.7))
       ENDIF
      RETURN
      END
