

C     HEAT TO CALCULATE THE HEAT TRANSPORT EQUATION
      SUBROUTINE HEAT (TPT,NDPT,NREF,DWMADT,WMAM,WMA,HAREA,FAREA,ACET
     1 ,IQSOP,VOL,POR,Y,YY,XX,QVYN,QLY,SW,RHO,TPT1,RHVS)
      USE M_PARAMS
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER NDPT(NSOP)
      INTEGER NREF(NSOP)
      COMMON /SOLVI/ KSOLVP, KSOLVU, NN1, NN2, NN3
      COMMON /DIMS/ NN,NE,NIN,NBI,NCBI,NB,NBHALF,NPBC,NUBC,
     1   NSOP,NSOU,NBCN,NCIDB
      COMMON /AERORESIS/ RAVT,RAVS,SWRAT
      COMMON /DEPTH/ MXD,NFY
      COMMON /ET/ QET,UET,PET,UVM,NGT,ITE,TMA,TMI,ALF,RS,RH,AP,BP,U2,
     1   TSD,SCF
      COMMON /CONTRL/ GNUP,GNUU,UP,DTMULT,DTMAX,ME,ISSFLO,ISSTRA,ITCYC, 
     1   NPCYC,NUCYC,NPRINT,NBCFPR,NBCSPR,NBCPPR,NBCUPR,IREAD,          
     2   ISTORE,NOUMAT,IUNSAT,KTYPE,MET,MAR,MSR,MSC,MHT,MVT,MFT,MRK
      COMMON /TIMES/ DELT,TSEC,TMIN,THOUR,TDAY,TWEEK,TMONTH,TYEAR,
     1   TMAX,DELTP,DELTU,DLTPM1,DLTUM1,IT,ITBCS,ITRST,ITMAX,TSTART
      COMMON /HEATPARA/ HSC,HER,ROUS,HCS
      DIMENSION KTYPE(2)
      DIMENSION TWMAM(NFY),TDWMADT(NFY),TFAREA(NFY)
      DIMENSION DWMADT(NN),WMAM(NN),HAREA(NSOP),FAREA(NSOP),TPT(NN)
     1  ,IQSOP(NSOP),VOL(NN),POR(NN),Y(NN),SW(NN),WMA(NN),RHO(NN)
      DIMENSION T2(NFY),SH(NFY),ACET(NFY),TVOL(NFY)
      DIMENSION QLY(NE),YY(NN),XX(NN)
      DIMENSION QVYN(NN1-1),RHVS(NN1)
      DIMENSION HC(NN1-1),TPT1(NN)
      DIMENSION RHSWN(NN1),DRSNDT(NN1)
      DIMENSION AA(NN1),BB(NN1),CC(NN1),ANS(NN1),UU(NN1)
C      DATA CL/4.186D3/, CP/2.D3/, CA/1.01D3/,DMAIR /2.897D-2/,
C     1     RC/8.314472D+0/,SATM /101.325D+3/
C      SAVE CL,CP,CA,DMAIR,RC,SATM
C     DRSNDT(NN1)-- D(RHO*SW*POR)/DT
C     RHSWN(NN1) -- RHO*SW*POR AT TIME STEP N+1
C     DMAIR -- MOLECULAR WEIGHT OF AIR 0.02897 [KG/MOL]
C     RC    -- GAS CONSTANT 8.314
C     SATM  -- STANDARD ATMOSPHERE PRESSURE [PA OR KG/M/S2 ]
C     HER -- LAYERS THAT CONSIDERS FOR THE HEAT BALANCE
C     ROUS -- SOIL DENSITY  [KG/M3]
C     HCS   -- HEAT CAPACITY OF THE SOIL 900 [J/KG/K]
C     CL   -- HEAT CAPACITY OF LIQUID WATER 4186  [J/KG/K]
C     CP   -- HEAT CAPACITY OF WATER VAPOR 2000 [J/KG/K]
      NSOPI=NSOP-1
 !USING THE PREVIOUS BULK METHOD. IT IS DELETED DUE TO STUIPITY
      IF (MHT.EQ.1)THEN      
C----------------------------------------------------------------------------------------------
 ! CALCULATING THE ONE DIMENSIONAL ENERGY TRANSPORT EQUATION USING
C   IMPLICIT FINITE DIFFERENCE SCHEME.
      ELSEIF (MHT.EQ.2)THEN
C    REFER TO SUMMERSCHOOL BOOK 1-8 AS WELL AS FILE
C    /SALTMARSH/CODEBOOK/HEATTRANSPORTALGORITHM.DOCX

C     CONVERTING VLY(NE) INTO QLY(NE)
C      CALL QLCONVERT(QLY,VLY,SW,POR)
C      CALCULATING HEAT CONDUCTANCE
      CALL HEATCOND(HC, POR,SW)
      DO 10 I=1,NN1
      RHSWN(I)=WMA(I)/VOL(I)
      DRSNDT(I)=DWMADT(I)/VOL(I)
10      CONTINUE
C     VLH  - LATENT HEAT FOR VAPORIZATION [J/KG]
C     TMAK - ATMOSPHEREIC TEMPERATURE IN [K]
C     TIK  - INITIAL SOIL TEMPERATURE [K]
C     TSDK - TEMPERATURE ON THE SIDE OF THE COLUMN [K]
      VLH=(2.50025-0.002365*(TMA))*1.D6 
      TMAK=TMA+273.15 
      TIK=TMI+273.15                  
      TSDK=TSD+273.15                 
C     MATRIX CALCULATION
      DO 11 I=2,NN1-1

      C1  =-HC(I-1)/YY(I)/(Y(I)-Y(I-1))
      QV1 =-CP*RHOW0*QVYN(I-1)/2.D0/YY(I)
      QL1 =-CL*QLY(I-1)*(RHO(I)+RHO(I-1))/4/YY(I)
      AA(I)=C1+QV1+QL1

      S2  =+(HCS*ROUS+CL*RHSWN(I))/DELT
      DT2 =+CL*DRSNDT(I)
      C2  =+(HC(I)/(Y(I+1)-Y(I))+HC(I-1)/(Y(I)-Y(I-1)))/YY(I)
      QV2 =+CP*RHOW0*(QVYN(I)-QVYN(I-1))/2.D0/YY(I)
      QL2 =+CL*(QLY(I)*(RHO(I+1)+RHO(I))-QLY(I-1)*(RHO(I)+RHO(I-1)))
     4        /4.D0/YY(I)
! XX(I) IS HEAT EMMISION IS FROM SIDE (YZ PLANE).SEE PAGE68 OF BOOK2012
      HS2 =+SCF*CA*SATM*DMAIR/RC/TSDK/RHVS(I)/XX(I) 
      BB(I)=S2+DT2+C2+QV2+QL2+HS2

      QV3 =+CP*RHOW0*QVYN(I)/2.D0/YY(I)
      QL3 =+CL*QLY(I)*(RHO(I+1)+RHO(I))/4.D0/YY(I)
      C3  =-HC(I)/YY(I)/(Y(I+1)-Y(I))
      CC(I)=QV3+QL3+C3

      SR  =+(HCS*ROUS+CL*RHSWN(I))/DELT*TPT(I)
      QVR =-RHOW0*(VLH-CP*TIK)*(QVYN(I)-QVYN(I-1))/YY(I)
      QLR =+CL*(QLY(I)*(RHO(I+1)+RHO(I))-QLY(I-1)*(RHO(I)+RHO(I-1))) 
     4        *TIK/2.D0/YY(I)
      DTR =+CL*TIK*DRSNDT(I)
      HSR =+SCF*CA*SATM*DMAIR/RC/RHVS(I)/XX(I)
 !XX(I) IS DUE TO HEAT EMMISION IS FROM SIDE (YZ PLANE)
      UU(I)=SR+QVR+QLR+DTR+HSR
11      CONTINUE
C-----------BOTTOM CELL ---------------
      I=1
      AA(I)=0.D0

      S2  = +(HCS*ROUS+CL*RHSWN(I))/DELT
      DT2 = +CL*DRSNDT(I)
      C2  = +(HC(I)/(Y(I+1)-Y(I)))/YY(I)         
      QV2 = +CP*RHOW0*(QVYN(I))/2.D0/YY(I)      
      QL2 = +CL*(QLY(I)*(RHO(I+1)+RHO(I)))/4.D0/YY(I)
      HS2 = +SCF*CA*SATM*DMAIR/RC/TSDK/RHVS(I)/XX(I)   
! THE XX(I)HEAT EMMISION IS FROM SIDE (YZ PLANE) RATHER THAN TOP 
C (XY PLANE)
      BB(I)=S2+DT2+C2+QV2+QL2+HS2

      QV3 = +CP*RHOW0*QVYN(I)/2.D0/YY(I)           
      QL3 = +CL*QLY(I)*(RHO(I+1)+RHO(I))/4.D0/YY(I)
      C3  = -HC(I)/YY(I)/(Y(I+1)-Y(I))            
      CC(I)=QV3+QL3+C3

      SR  = +(HCS*ROUS+CL*RHSWN(I))/DELT*TPT(I) 
      QVR = -RHOW0*(VLH-CP*TIK)*(QVYN(I))/YY(I) 
      QLR = +CL*(QLY(I)*(RHO(I+1)+RHO(I)))*TIK/2.D0/YY(I)              
      DTR = +CL*TIK*DRSNDT(I)                   
      HSR = +SCF*CA*SATM*DMAIR/RC/RHVS(I)/XX(I)  
!THE XX(I) HEAT EMMISION IS FROM SIDE (YZ PLANE) RATHER THAN TOP
C (XY PLANE)
      UU(I)=SR+QVR+QLR+DTR+HSR

C-----------TOP CELL ---------------
      I=NN1
     
      C1  = -HC(I-1)/YY(I)/(Y(I)-Y(I-1))    
      QV1 = -CP*RHOW0*QVYN(I-1)/2.D0/YY(I)  
      QL1 = -CL*QLY(I-1)*(RHO(I)+RHO(I-1))/4/YY(I)
      AA(I)=C1+QV1+QL1

      S2  = +(HCS*ROUS+CL*RHSWN(I))/DELT     
      DT2 = +CL*DRSNDT(I)                    
      C2  = +(HC(I-1)/(Y(I)-Y(I-1)))/YY(I)   
      QV2 = +CP*RHOW0*(-QVYN(I-1))/2.D0/YY(I)
      QL2 = +CL*(-QLY(I-1)*(RHO(I)+RHO(I-1)))/4.D0/YY(I)            
      HS2 = +SCF*CA*SATM*DMAIR/RC/TSDK/RHVS(I)/XX(I)
C !SCF--SCALING EFFECT H2
      HT2 = +SWRAT*CA*SATM*DMAIR/RC/TMAK/RAVT/YY(I)     
C   ! HEAT EXCHANGE FROM THE TOP
      BB(I)=S2+DT2+C2+QV2+QL2+HS2+HT2

      CC(I)=0.D0

      SR  = +(HCS*ROUS+CL*RHSWN(I))/DELT*TPT(I)
      QVR = -RHOW0*(VLH-CP*TIK)*(-QVYN(I-1))/YY(I)
      QLR = +CL*(-QLY(I-1)*(RHO(I)+RHO(I-1)))*TIK/2.D0/YY(I)
      DTR = +CL*TIK*DRSNDT(I)                     
      HSR = +SCF*CA*SATM*DMAIR/RC/RHVS(I)/XX(I)   
!THE XX(I) THE HEAT EMMISION IS FROM SIDE (YZ PLANE) RATHER THAN TOP 
C(XY PLANE)
      HTR = +SWRAT*CA*SATM*DMAIR/RC/RAVT/YY(I)
      HRTR= +HSC/YY(I)                            
!HEAT SOURCE HSC IS ADDED， WARNING, HERE HEAT SOURCE IS CALCULATED 
CEXPLICITELY!
      LHTR= +ACET(1)*VLH*RHOW0/YY(I)               
!LHTR!EVAPORATION INDUCED LATENT HEAT, ACET IS NEGATIVE
      UU(I)=SR+QVR+QLR+DTR+HSR+HTR+HRTR+LHTR

      CALL TRIDAG(AA,BB,CC,UU,ANS,NN1)
      
C     RETURN THE VALUE BACK INTO TPT MATRIX AND STORE THE LAST 
C     TEMPERATURE VALUE INTO TPT1
      K=0
      DO 15 J=1,NN2 !LOOP ON X
      DO 7 I=1,NN1  !LOOP ON Y
      K=K+1
      TPT1(K)=TPT(K)
      TPT(K)=ANS(I)


7      CONTINUE
15      CONTINUE
C-----------------------------------------------------
      ELSEIF (MHT.EQ.3)THEN ! USING THE INITIAL TEMPATURE
      
      ENDIF

      RETURN
      END
