MODULE MOD_SURFR
 IMPLICIT NONE

 DOUBLE PRECISION :: TAL,EC,ETR
! THE MATRIC POTENTIAL AT THE BEGINNING OF STAGE IV
 DOUBLE PRECISION :: PSIP
! COEFFICIENT APPLIED WHEN MSR=7
 DOUBLE PRECISION :: COER
 SAVE
END MODULE MOD_SURFR


 MODULE M_PARAMS
    IMPLICIT NONE
    DOUBLE PRECISION ::COMPFL,COMPMA,DRWDU,CW,CS,RHOS,SIGMAW,SIGMAS
    DOUBLE PRECISION ::RHOW0,URHOW0,VISC0,PRODF1,PRODS1,PRODF0
    DOUBLE PRECISION :: PRODS0,CHI1,CHI2,DVIDU
!(VAC)CUM (PERM)EABILITY [PERMFS] [C2J-1M-1 OR F/M OR S4A2/KG/M3] 
!   nSEE PAGE 165
    DOUBLE PRECISION,PARAMETER :: PERMVAC=8.854D-12
!   (R)ELATIVE (PERM)EABILITY OF (W)ATER (RELPW)  [-]
    DOUBLE PRECISION,PARAMETER :: RELPW=78.54D0
!   (SURF)ACE (T)ENTION AT 20 CELSIUST [J/M2 OR N/M]
    DOUBLE PRECISION ,PARAMETER:: SURFT=0.072D0
!    PI
    DOUBLE PRECISION,PARAMETER :: PI=3.141592653589793D0
!    (ELECTR)ON (C)HARGE   (ELECTRC) [COULOMBS OR AS]
    DOUBLE PRECISION,PARAMETER :: ELECTRC=1.602D-19
!    (BOTZ)MANN (C)ONSTANT (BOTZC)  [J/K]
    DOUBLE PRECISION,PARAMETER :: BOTZC=1.381D-23
!    HEAT (C)APACITY OF (L)IQUID WATER (CL) [J/KG/K]
    DOUBLE PRECISION,PARAMETER :: CL=4.186D3
!    HEAT (C)APACITY OF WATER VA(P)OR (CP) [J/KG/K]
    DOUBLE PRECISION,PARAMETER :: CP=2.0D3
!    HEAT (C)APACITY OF (A)IR (CA)  [J/KG/K]
    DOUBLE PRECISION,PARAMETER :: CA=1.01D3
!    (M)OLECULAR WEIGHT OF (AIR) (DMAIR) 
    DOUBLE PRECISION,PARAMETER ::DMAIR=2.897D-2
!    (C)ONSTANT OF IDEALIZED GAS (RC) [J/MOL/K]
    DOUBLE PRECISION,PARAMETER ::RC=8.314472D+0
!    (S)TANDARD (ATM)OSPHERE PRESSURE (SATM) [PA]
    DOUBLE PRECISION,PARAMETER ::SATM=1.01325D5
!    (M)OLECULAR WEIGHT OF (S)AL(T) (MST)
    DOUBLE PRECISION,PARAMETER ::STM=5.85D-2
!    (G)RAVITIONAL (A)CCERLATION
    DOUBLE PRECISION,PARAMETER ::GVA=9.8D0
!    (W)ATER (M)OLECULAR (W)EIGHT
    DOUBLE PRECISION,PARAMETER ::WMW=1.8D-2
!    COSTANTS USED IN YOUNG-LAPLACE EQUATION
!    THIS NEGATIVE SYMBOL KILL ONE DAY FROM ME. NOW IT IS ALL NEGATIVE VALUE 160531
    DOUBLE PRECISION,PARAMETER ::ZETA=-1.46789D-5

    SAVE
  END MODULE M_PARAMS
