
!  FUNCTION TO CALCULATE SURFACE RESISTANCE 
!  WHEN MSR=0, SYRFSIS=0
!  WHEN MSR=1, USING CAMILO(1986) FORMULAR
!  WHEN MSR=2, USING SUN (1982) FORMULAR
!  WHEN MSR=3, USING DAAMEN (1996) FORMULAR
!  WHEN MSR=4, USING VAN DER GRIEND (1994) FORMULAR
!  WHEN MSR=5, USING HYPERGEOMETRIC FUNCTIONS SEE PAGE 142 OF 
!              BLUEBOOK, 98(5)
!  WHEN MSR=6, USING APPROXIMATED EQUATION GIVEN BY PAPER 2, USING THE
!      POTENTIAL RESULT AT THE TOPMOST CELL
!  WHEN MSR=7, USING APPROXIMATED EQUATION GIVEN BY PAPER 2, USING THE
!      HYDRAUSTATIC PRESSURE DISTRIBUTION AT THE TOPMOST CELL
   DOUBLE PRECISION FUNCTION SURFRSIS(PP,POR,SW,MSR,KREG,TSK,Y)
   IMPLICIT DOUBLE PRECISION (A-H,O-Z)
   COMMON /UNSA/ SWRES1,AA1,VN1,SWRES2,AA2,VN2,SWRES3,DLAM3,PHICB3, &
  SWRES4,DLAM4,PHICB4,PHIC0,ECTO
   COMMON /SURFR/ TAL,EC,ETR 
   COMMON /AERORESIS/ RAVT,RAVS,SWRAT
   COMMON /PARAMS/ COMPFL,COMPMA,DRWDU,CW,CS,RHOS,SIGMAW,SIGMAS,  &
     RHOW0,URHOW0,VISC0,PRODF1,PRODS1,PRODF0,PRODS0,CHI1,CHI2,   &
     DVIDU,RELPW,PERMVAC,SURFT,PI,ELECTRC,BOTZC,CL,CA,DMAIR,     &
     RC,SATM,STM,GVA,WMW,ZETA
! PP --PORE WATER PRESSURE
   IF (MSR.EQ.0) THEN
   SURFRSIS=0.D0
   ELSEIF(MSR.EQ.1)THEN
   SURFRSIS=-8.05D2+4.14D3*POR*(1-SW)
   ELSEIF(MSR.EQ.2)THEN
   SURFRSIS=3.5D0*SW**(-2.3D0)+33.5D0
   ELSEIF(MSR.EQ.3)THEN
   SURFRSIS=3.D10*(POR*(1-SW))**16.6D0
   ELSEIF(MSR.EQ.4)THEN
   SURFRSIS=10.D0*EXP(35.63D0*POR*(0.375D0-SW))
!  SEE PAGE 98(4) FOR REFERENCE
   ELSEIF(MSR.EQ.5)THEN
!  AA IS THE FIRST ARGUMENT OF THE HYPERGEOMETRIC FUNCTION WARNING:
!    ONE SHOULD INPUT A VARIABLE IN
!    FUNCTION HYGFX RATHER THAN A VALUE!!!
     AA=1.D0
!  CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD
!    (M)
     PHIC=-PP/9.8D3
!    CHECKING THE SOIL CHARACTERISTIC PARAMETERS
     IF(KREG.EQ.3)THEN
       DLAM=DLAM3
       PHICB=PHICB3
     ELSEIF(KERG.EQ.4)THEN
       DLAM=DLAM4   
       PHICB=PHICB4   
     ENDIF
!    EVALUATING RS BY DIFFERENT PHIC VALUE
     IF (PHIC.LE.PHICB)THEN
       SURFRSIS=0.D0
     ELSEIF (PHIC.GT.PHICB)THEN
       ETI=ETR*DLOG(PHIC0/PHIC)/DLOG(PHIC0)
       ETRMS=1.D0-ETI
       ETB=ETR*DLOG(PHIC0/PHICB)/DLOG(PHIC0)
       ETBMS=1.D0-ETB
!      (E)FFECTIVE (S)ATURATION
       SE=(PHICB/PHIC)**DLAM
!      PORSE
       PORSE=POR*SE
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
!      PARAMETER WHEN SE=1
       C0=(1/POR-1/SQRT(POR))/2.D0/TAL
       DNUM=SE**EC*HYGFX(AA,DLAM,1+DLAM,-C*ZETA/PHIC)*ETRMS+ETI
       DNOM=HYGFX(AA,DLAM,1+DLAM,-C0*ZETA/PHICB)*ETBMS+ETB
       DNET=DNUM/DNOM
! IS A QUESTION WHY THE EQUATION IS FORMULATED AS THIS?
       SURFRSIS=RAVT/DNET-RAVT
     ENDIF
! SURFACE RESISTANCE AFTER THE APPROXIMATION SEE PAGE 
   ELSEIF(MSR.EQ.6.OR.MSR.EQ.7)THEN
!  CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD 
!    (M)
     IF (MSR.EQ.6)THEN
     PHIC=-PP/GVA/RHOW0
! THIS IS A STUPID WAY OF DOING. ACCORDING TO SHAPE FUNCTION, PHIC 
! EQUALS TO THE VALUE AT THE NODE, SO Y/2.D0 DOESN'T MAKE SENCE
     ELSEIF(MSR.EQ.7)THEN
     PHIC=-PP/GVA/RHOW0+Y/2.D0
     ENDIF
!    CHECKING THE SOIL CHARACTERISTIC PARAMETERS
     IF(KREG.EQ.3)THEN
       DLAM=DLAM3
       PHICB=PHICB3
     ELSEIF(KERG.EQ.4)THEN
       DLAM=DLAM4   
       PHICB=PHICB4   
     ENDIF
!    EVALUATING RS BY DIFFERENT PHIC VALUE
     IF (PHIC.LE.PHICB)THEN
       SURFRSIS=0.D0
     ELSEIF (PHIC.GT.PHICB)THEN
       ETI=ETR*DLOG(PHIC0/PHIC)/DLOG(PHIC0)
       ETRMS=1.D0-ETI
!      (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
       SET=(PHICB/PHIC)**(DLAM*(1+EC))
!      POR*SET
       PORSE=POR*SET
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
!      EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
!      (UNDER BROOKS&COREY)
!      SEE EQUATION (A1) OF PAPER 2
       R1EFF=DLAM*ZETA/(DLAM+1)/PHIC
       RELKV=1/(1+C*R1EFF)*ETRMS+ETI
       SURFRSIS=TAL/DVA(TSK)/RELKV
     ENDIF
   ENDIF
   IF (SURFRSIS.LT.0.D0) SURFRSIS=0.D0
   RETURN 
   END FUNCTION SURFRSIS

