
C     FUNCTION TO CALCULATE SURFACE RESISTANCE 
C     WHEN MSR=0, SYRFSIS=0
C     WHEN MSR=1, USING CAMILO(1986) FORMULAR
C     WHEN MSR=2, USING SUN (1982) FORMULAR
C     WHEN MSR=3, USING DAAMEN (1996) FORMULAR
C     WHEN MSR=4, USING VAN DER GRIEND (1994) FORMULAR
C     WHEN MSR=5, USING HYPERGEOMETRIC FUNCTIONS SEE PAGE 142 OF 
C                 BLUEBOOK, 98(5)
C     WHEN MSR=6, USING APPROXIMATED EQUATION GIVEN BY PAPER 2
      DOUBLE PRECISION FUNCTION SURFRSIS(PP,POR,SW,MSR,KREG,TSK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /UNSA/ SWRES1,AA1,VN1,SWRES2,AA2,VN2,SWRES3,DLAM3,PHICB3,
     1SWRES4,DLAM4,PHICB4,PHIC0,ECTO
      COMMON /SURFR/ TAL,EC,ETR 
      COMMON /AERORESIS/ RAVT,RAVS,SWRAT
      COMMON /PARAMS/ COMPFL,COMPMA,DRWDU,CW,CS,RHOS,SIGMAW,SIGMAS,
     1   RHOW0,URHOW0,VISC0,PRODF1,PRODS1,PRODF0,PRODS0,CHI1,CHI2,
     2   DVIDU,RELPW,PERMVAC,SURFT,PI,ELECTRC,BOTZC,CL,CA,DMAIR,
     3   RC,SATM,STM,GVA,WMW,ZETA
C    PP --PORE WATER PRESSURE
      IF (MSR.EQ.0) THEN
      SURFRSIS=0.D0
      ELSEIF(MSR.EQ.1)THEN
      SURFRSIS=-8.05D2+4.14D3*POR*(1-SW)
      ELSEIF(MSR.EQ.2)THEN
      SURFRSIS=3.5D0*SW**(-2.3D0)+33.5D0
      ELSEIF(MSR.EQ.3)THEN
      SURFRSIS=3.D10*(POR*(1-SW))**16.6D0
      ELSEIF(MSR.EQ.4)THEN
      SURFRSIS=10.D0*EXP(35.63D0*POR*(0.375D0-SW))
C     SEE PAGE 98(4) FOR REFERENCE
      ELSEIF(MSR.EQ.5)THEN
C       AA IS THE FIRST ARGUMENT OF THE HYPERGEOMETRIC FUNCTION WARNING:
C       ONE SHOULD INPUT A VARIABLE IN
C       FUNCTION HYGFX RATHER THAN A VALUE!!!
        AA=1.D0
C       CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD
C       (M)
        PHIC=-PP/9.8D3
C       CHECKING THE SOIL CHARACTERISTIC PARAMETERS
        IF(KREG.EQ.3)THEN
          DLAM=DLAM3
          PHICB=PHICB3
        ELSEIF(KERG.EQ.4)THEN
          DLAM=DLAM4   
          PHICB=PHICB4   
        ENDIF
C       EVALUATING RS BY DIFFERENT PHIC VALUE
        IF (PHIC.LE.PHICB)THEN
          SURFRSIS=0.D0
        ELSEIF (PHIC.GT.PHICB)THEN
          ETI=ETR*DLOG(PHIC0/PHIC)/DLOG(PHIC0)
          ETRMS=1.D0-ETI
          ETB=ETR*DLOG(PHIC0/PHICB)/DLOG(PHIC0)
          ETBMS=1.D0-ETB
C         (E)FFECTIVE (S)ATURATION
          SE=(PHICB/PHIC)**DLAM
C         PORSE
          PORSE=POR*SE
C         PARAMETER IN THE HYPERGEOMETRIC
          C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
C         PARAMETER WHEN SE=1
          C0=(1/POR-1/SQRT(POR))/2.D0/TAL
          DNUM=SE**EC*HYGFX(AA,DLAM,1+DLAM,-C*ZETA/PHIC)*ETRMS+ETI
          DNOM=HYGFX(AA,DLAM,1+DLAM,-C0*ZETA/PHICB)*ETBMS+ETB
          DNET=DNUM/DNOM
C IT IS A QUESTION WHY THE EQUATION IS FORMULATED AS THIS?
          SURFRSIS=RAVT/DNET-RAVT
        ENDIF
C    SURFACE RESISTANCE AFTER THE APPROXIMATION SEE PAGE 
      ELSEIF(MSR.EQ.6)THEN
C       CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD 
C       (M)
        PHIC=-PP/9.8D3
C       CHECKING THE SOIL CHARACTERISTIC PARAMETERS
        IF(KREG.EQ.3)THEN
          DLAM=DLAM3
          PHICB=PHICB3
        ELSEIF(KERG.EQ.4)THEN
          DLAM=DLAM4   
          PHICB=PHICB4   
        ENDIF
C       EVALUATING RS BY DIFFERENT PHIC VALUE
        IF (PHIC.LE.PHICB)THEN
          SURFRSIS=0.D0
        ELSEIF (PHIC.GT.PHICB)THEN
          ETI=ETR*DLOG(PHIC0/PHIC)/DLOG(PHIC0)
          ETRMS=1.D0-ETI
C         (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
          SET=(PHICB/PHIC)**(DLAM*(1+EC))
C         POR*SET
          PORSE=POR*SET
C         PARAMETER IN THE HYPERGEOMETRIC
          C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
C         EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
C         (UNDER BROOKS&COREY)
C         SEE EQUATION (A1) OF PAPER 2
          R1EFF=DLAM*ZETA/(DLAM+1)/PHIC
          RELKV=1/(1+C*R1EFF)*ETRMS+ETI
          SURFRSIS=TAL/DA(TSK)/RELKV
        ENDIF


      ENDIF


      IF (SURFRSIS.LT.0.D0) SURFRSIS=0.D0
      RETURN 
      END

