C     TRIDIAG IS TO SOLVE TRADIAGNAL MATRIX
C     THIS IS OBTAINED FROM NUMERICAL RECIPIE
      SUBROUTINE TRIDAG(A,B,C,R,U,N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER N,NMAX
      DIMENSION A(N),B(N),C(N),R(N),U(N)
      PARAMETER (NMAX=500)
C      SOLVES FOR A VECTOR U(1:N) OF LENGTH N THE TRIDIAGONAL LINEAR SET GIVEN BY EQUATION (2.4.1).
C      A(1:N), B(1:N), C(1:N), AND R(1:N) ARE INPUT VECTORS AND ARE NOT MODIFED.
C      PARAMETER: NMAX IS THE MAXIMUM EXPECTED VALUE OF N.
      INTEGER J
      DIMENSION GAM(NMAX) !ONE VECTOR OF WORKSPACE, GAM IS NEEDED.
C      IF(B(1).EQ.0.)PAUSE !TRIDAG: REWRITE EQUATIONS'
C     IF THIS HAPPENS THEN YOU SHOULD REWRITE YOUR EQUATIONS AS A SET OF ORDER N - 1, WITH U2
C     TRIVIALLY ELIMINATED.
      BET=B(1)
      U(1)=R(1)/BET
      DO 11 J=2,N !DECOMPOSITION AND FORWARD SUBSTITUTION.
      GAM(J)=C(J-1)/BET
      BET=B(J)-A(J)*GAM(J)
C      IF(BET.EQ.0.)PAUSE !TRIDAG FAILED' ALGORITHM FAILS; SEE BELOW.
      U(J)=(R(J)-A(J)*U(J-1))/BET
11      ENDDO 
      DO 12 J=N-1,1,-1 !BACKSUBSTITUTION.
      U(J)=U(J)-GAM(J+1)*U(J+1)
12    ENDDO
      RETURN
      END
