C    ---CALCULATING VAPOR FLUX BETWEEN TWO NEIGHBOURING NODE--------
C    CALLED SUBROUTINES INCLUDING DV, XX, 
C    SEE NOTEBOOK3 P43,P108 IN YEAR 2012, ALSO VERIFIED AT JAN 2013
      SUBROUTINE VAPOR (AET,SW1,SW2,P1,P2,U1,U2,POR1,POR2,T1,T2,X1,X2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)                               
      COMMON /PARAMS/ COMPFL,COMPMA,DRWDU,CW,CS,RHOS,SIGMAW,SIGMAS,
     1   RHOW0,URHOW0,VISC0,PRODF1,PRODS1,PRODF0,PRODS0,CHI1,CHI2,
     2   DVIDU,RELPW,PERMVAC,SURFT,PI,ELECTRC,BOTZC,CL,CA,DMAIR,
     3   RC,SATM,STM,GVA,WMW,ZETA
      DIMENSION KTYPE(2)
C     AET  -- ACTUAL EVAPORATION RATE [MM/DAY]
C     P1,P2   -- PRESSURE AT THE SPECIFIED NODE [KG/M/S2]
C     U1,U2   -- CONCENTRATION AT THE SPECIFIED NODE  [KG/KG]
C     T1,T2   -- TEMPERATURE AT EACH NODE
C     ED   -- SATURATED VAPOUR PRESSURE AT DEW POINT [KPA]
C     EO(NOT ZERO)   -- SATURATED VAPOUR PRESSURE AT MEAN DAILY AIR
C      TEMP.  [PA]
C     RC   -- UNIVERSAL GAS CONSTANT [J/MOL/K]
C     WMW   -- MOLECULAR WEIGHT OF WATER [KG/MOL]
C     TSD   -- TEMPERATURE ON THE SIDE OF THE HEAT COLUMN [CELSIUS]
C     STM  -- MOLECULAR WEIGHT OF NACL [KG/MOL]
C     RHOW0   -- INITIAL WATER DENSITY 1000 (KG/M3)
C     G    -- GRAVATIONAL ACCERATION 9.8 (M/S2)

C     TK=TMI+273.15D0                   ! SOIL SURFACE TEMPERATURE
      SWM=(SW1+SW2)/2.D0
      PM=(P1+P2)/2.D0
      UM=(U1+U2)/2.D0
      PORM=(POR1+POR2)/2.D0
      TM=(T1+T2)/2.D0
      DX=X1-X2
      DTDX=(T1-T2)/DX
      DCDX=(CHI(U1)*U1-CHI(U2)*U2)/DX
      DPDX=(P1-P2)/DX
C ...   HERE THE FIRST ARGUMENT OF YITA DETERMINES THE LOCATION OF YITA 
C       AT=DV(PORM,SWM,TM)*PSAT(1,TM)*WMW*
C     1  HR(FYM(PM),FYO(UM,TM),TM)/RHOW0/TM/RC
C       A1= -YITA(1,SWM)*DPDX*WMW/(RHOW0*RC*TM)
C       A2= +YITA(2,SWM)*2.D0*WMW*DCDX/STM
C       A3= -YITA(3,SWM)*DTDX*(PSAT(2,TM)/PSAT(1,TM)-1.D0/TM)
C       A4= +YITA(4,SWM)*FYM(PM)*GVA*WMW*DTDX/(RC*TM**2.D0) 
C     THE FOLLOWING SCRIPTS ARE BASED ON PHOWVSAT, WHICH IS MORE EASIER
C     TO CONSTRUCT. SEE PAGE 222-223 FOR REFERENCE
      AT=-DVA(TM)*TAO(PORM,SWM)*THEA(PORM,SWM)*RHOWVSAT(1,TM)*
     1HR(FYM(PM),FYO(UM,TM),TM)/RHOW0
      A1=+YITA(1,SWM)*WMW/(RHOW0*RC*TM)*DPDX
      A2=-YITA(2,SWM)*2.D0*WMW/STM*DCDX
      A3=+YITA(3,SWM)*RHOWVSAT(2,TM)/RHOWVSAT(1,TM)*DTDX
      A4=-YITA(4,SWM)*FYM(PM)*GVA*WMW/(RC*TM**2.D0)*DTDX
!RELATIVE HUMIDITY INDUCED BY OSMOTIC IS NOT A FUNCTION OF T SEE NB3P108
       AET=AT*(A1+A2+A3+A4)
      RETURN
      END
